#!/bin/bash
# Proves that the tests are not decor: for every invariant I1-I12 plus the three
# executante-brief interdicts (AskUserQuestion, self-validation, irreversible act),
# apply a single textual mutation to ordo/, run the test named after that invariant,
# and require it to fail. A test that stays green under mutation proves nothing and
# is reported by name, loudly, as a script failure.
#
# Every mutation is a single search/replace on an exact, unique substring of a
# ordo/*.py file -- never a line number, since lines move and patterns mostly do not.
# If a pattern is not found, or found more than once, the script aborts that case
# loudly instead of mutating something unintended.
#
# Restoration is guaranteed even on Ctrl-C or a crashing test: each case backs up
# its target file before mutating and restores it immediately after, and a trap on
# EXIT/INT/TERM restores whatever is still mutated if the script is interrupted
# mid-case. A final pass diffs the whole ordo/ tree against a pristine snapshot taken
# before the first mutation and repairs anything left out of place.
#
# Runs from any working directory: paths are resolved from this script's own
# location, never from $PWD.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORDO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LIB_DIR="$ORDO_ROOT/ordo"

WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/ordo-mutation-check.XXXXXX")"
SNAPSHOT_DIR="$WORKDIR/snapshot"
mkdir -p "$SNAPSHOT_DIR"
cp -R "$LIB_DIR"/. "$SNAPSHOT_DIR"/
find "$SNAPSHOT_DIR" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null

# Files this script never mutates and that the OS rewrites on its own. Comparing them
# turns a healthy run into a false "ECART DETECTE": macOS touches .DS_Store whenever the
# directory is browsed, and .pyc files are regenerated by the very tests run below.
DIFF_IGNORE=(-x __pycache__ -x "*.pyc" -x .DS_Store)
find "$SNAPSHOT_DIR" -name .DS_Store -delete 2>/dev/null

# State of whatever mutation is currently in flight, so the trap below can restore
# it even if the script dies mid-case (Ctrl-C, a crashing test, anything). Cleared
# by run_case() itself on every normal exit from a case.
CURRENT_FILE=""
CURRENT_BACKUP=""
RESTORE_ALREADY_DONE=0

TOTAL=0
COUVERTS=0
NON_COUVERTS=0
declare -a NON_COUVERTS_NOMS=()

restore_lib_tree() {
    # Final safety net: whatever the per-case restores did or did not manage, the
    # whole ordo/ tree must match the pristine snapshot taken before case 1. Ignores
    # __pycache__ and .DS_Store, neither of which was ever mutated: see DIFF_IGNORE.
    find "$LIB_DIR" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null
    if diff -rq "${DIFF_IGNORE[@]}" "$SNAPSHOT_DIR" "$LIB_DIR" >/dev/null 2>&1; then
        echo "restauration confirmee : ordo/ est identique a la copie de sauvegarde initiale."
        return 0
    fi
    echo "ECART DETECTE apres execution, restauration forcee depuis la copie initiale :" >&2
    diff -rq "${DIFF_IGNORE[@]}" "$SNAPSHOT_DIR" "$LIB_DIR" >&2
    cp -R "$SNAPSHOT_DIR"/. "$LIB_DIR"/
    if diff -rq "${DIFF_IGNORE[@]}" "$SNAPSHOT_DIR" "$LIB_DIR" >/dev/null 2>&1; then
        echo "restauration forcee reussie : ordo/ est de nouveau identique a la copie initiale." >&2
        return 0
    fi
    echo "RESTAURATION IMPOSSIBLE : ordo/ reste different de la copie de sauvegarde." >&2
    return 1
}

CLEANUP_RAN=0

# $1, if given, forces the exit code (used by the signal handlers below: an
# interrupted run is never a success, regardless of whatever $? happened to be on
# whatever command the signal landed on). Left empty on a plain EXIT trap, so a
# normal end of script keeps the code main() already decided.
cleanup() {
    local rc="${1:-$?}"

    # exit called from inside a signal-triggered run of this handler fires the
    # EXIT trap too, which is this same function: without this guard, the second
    # pass finds $WORKDIR already removed by the first pass and reports a false
    # restoration failure against a snapshot directory that is simply gone. The
    # exit code from the FIRST call is what the shell actually reports; a bare
    # `return` here does not change it.
    if [ "$CLEANUP_RAN" -eq 1 ]; then
        return "$rc"
    fi
    CLEANUP_RAN=1

    if [ -n "$CURRENT_FILE" ] && [ -n "$CURRENT_BACKUP" ] && [ -f "$CURRENT_BACKUP" ]; then
        echo "" >&2
        echo "interruption : restauration d'urgence de $CURRENT_FILE" >&2
        cp "$CURRENT_BACKUP" "$CURRENT_FILE"
        CURRENT_FILE=""
        CURRENT_BACKUP=""
    fi
    if [ "$RESTORE_ALREADY_DONE" -ne 1 ]; then
        restore_lib_tree || rc=1
    fi
    rm -rf "$WORKDIR"
    exit "$rc"
}

on_signal() {
    echo "" >&2
    echo "interrompu (signal $1), restauration en cours..." >&2
    cleanup 1
}

trap cleanup EXIT
trap 'on_signal INT' INT
trap 'on_signal TERM' TERM

# Applies one search/replace mutation to $1, runs the unittest target $4, and
# requires it to fail (go red). $2/$3 are files holding the exact search and
# replace text (read from files, never shell arguments, so accented French text,
# quotes and backslashes never need shell escaping). Always restores $1 before
# returning, success or failure.
run_case() {
    local id="$1" desc="$2" testid="$3" file="$4" search_tmp="$5" replace_tmp="$6"
    TOTAL=$((TOTAL + 1))

    if [ ! -f "$file" ]; then
        printf '%-5s %-58s NON COUVERT (fichier introuvable : %s)\n' "$id" "$desc" "$file"
        NON_COUVERTS=$((NON_COUVERTS + 1))
        NON_COUVERTS_NOMS+=("$id ($desc) : fichier introuvable")
        return
    fi

    # Baseline: the target test must already be green before mutating anything.
    # A test that is already red proves nothing about the mutation.
    if ! (cd "$ORDO_ROOT" && python3 -m unittest "$testid") >"$WORKDIR/pre.out" 2>&1; then
        printf '%-5s %-58s NON COUVERT (test deja rouge avant mutation : %s)\n' "$id" "$desc" "$testid"
        NON_COUVERTS=$((NON_COUVERTS + 1))
        NON_COUVERTS_NOMS+=("$id ($desc) : $testid rouge avant toute mutation")
        return
    fi

    local backup mut_err
    backup="$(mktemp "$WORKDIR/backup.XXXXXX")"
    mut_err="$(mktemp "$WORKDIR/muterr.XXXXXX")"
    cp "$file" "$backup"

    if ! python3 - "$file" "$search_tmp" "$replace_tmp" >/dev/null 2>"$mut_err" <<'PYEOF'
import sys
import pathlib

target, search_path, replace_path = sys.argv[1], sys.argv[2], sys.argv[3]
search = pathlib.Path(search_path).read_text(encoding="utf-8")
replace = pathlib.Path(replace_path).read_text(encoding="utf-8")
text = pathlib.Path(target).read_text(encoding="utf-8")
count = text.count(search)
if count != 1:
    sys.stderr.write(
        "motif trouve %d fois dans %s (attendu exactement 1)" % (count, target)
    )
    sys.exit(2)
pathlib.Path(target).write_text(text.replace(search, replace, 1), encoding="utf-8")
PYEOF
    then
        printf '%-5s %-58s NON COUVERT (%s)\n' "$id" "$desc" "$(cat "$mut_err")"
        NON_COUVERTS=$((NON_COUVERTS + 1))
        NON_COUVERTS_NOMS+=("$id ($desc) : $(cat "$mut_err")")
        rm -f "$backup" "$mut_err"
        return
    fi
    rm -f "$mut_err"

    CURRENT_FILE="$file"
    CURRENT_BACKUP="$backup"

    if (cd "$ORDO_ROOT" && python3 -m unittest "$testid") >"$WORKDIR/post.out" 2>&1; then
        printf '%-5s %-58s ECHEC (%s reste VERT sous mutation : ne prouve rien)\n' "$id" "$desc" "$testid"
        NON_COUVERTS=$((NON_COUVERTS + 1))
        NON_COUVERTS_NOMS+=("$id ($desc) : $testid reste vert sous mutation")
    else
        printf '%-5s %-58s PROUVE (%s passe au ROUGE sous mutation)\n' "$id" "$desc" "$testid"
        COUVERTS=$((COUVERTS + 1))
    fi

    cp "$CURRENT_BACKUP" "$CURRENT_FILE"
    rm -f "$CURRENT_BACKUP"
    CURRENT_FILE=""
    CURRENT_BACKUP=""
}

echo "Verification par mutation, socle ~/.claude/ordo"
echo "ordo/  : $LIB_DIR"
echo "tests : $ORDO_ROOT/tests"
echo ""

# ---------------------------------------------------------------------------
# I1 -- la checklist d'une tache est une POST-condition, jamais une precondition
# pour elle-meme. Mutation : ready()/_dependencies_satisfied() cesse de regarder
# la checklist des dependances, seulement leur etat "done".
# ---------------------------------------------------------------------------
S="$WORKDIR/s01"; R="$WORKDIR/r01"
cat >"$S" <<'ORDO_EOF'
        if not all(item["done"] for item in dep["checklist"]):
            return False
ORDO_EOF
: >"$R"
run_case "I1" "checklist = post-condition, jamais precondition" \
    "tests.test_chantier.TestReady.test_i1_checklist_est_une_post_condition" \
    "$LIB_DIR/chantier.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I2 -- le rapport est le signal, un rapport illisible bloque, il ne laisse
# jamais passer pour reussi. Mutation : report.apply() marque "done" au lieu de
# "blocked" quand parse() a leve.
# ---------------------------------------------------------------------------
S="$WORKDIR/s02"; R="$WORKDIR/r02"
cat >"$S" <<'ORDO_EOF'
        task["state"] = "blocked"
        task["error"] = f"unreadable report: {exc}"
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        task["state"] = "done"
        task["error"] = f"unreadable report: {exc}"
ORDO_EOF
run_case "I2" "rapport illisible bloque, jamais reussi" \
    "tests.test_report.TestApplyIllisible.test_i2_rapport_illisible_bloque_jamais_reussi" \
    "$LIB_DIR/report.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I3 -- tout chemin passe par canon() avant d'etre stocke ou compare. Mutation :
# canon() cesse de resoudre les liens symboliques (realpath retire).
# ---------------------------------------------------------------------------
S="$WORKDIR/s03"; R="$WORKDIR/r03"
cat >"$S" <<'ORDO_EOF'
    return os.path.realpath(os.path.expanduser(s))
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    return os.path.expanduser(s)
ORDO_EOF
run_case "I3" "canon() resout les liens symboliques" \
    "tests.test_store.TestCanon.test_i3_canon_resout_les_liens_symboliques" \
    "$LIB_DIR/store.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I4 -- le prompt part par stdin, jamais en argument positionnel. Mutation :
# plan.propose() ajoute le pave dans l'argv de la commande claude.
# ---------------------------------------------------------------------------
S="$WORKDIR/s04"; R="$WORKDIR/r04"
cat >"$S" <<'ORDO_EOF'
    cmd = ["claude", "-p", "--output-format", "json", "--json-schema", PLAN_SCHEMA,
           "--model", model]
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    cmd = ["claude", "-p", "--output-format", "json", "--json-schema", PLAN_SCHEMA,
           "--model", model, pave]
ORDO_EOF
run_case "I4" "le pave part par stdin, jamais en argument" \
    "tests.test_plan.TestPropose.test_propose_sends_pave_via_stdin_never_in_argv" \
    "$LIB_DIR/plan.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I5 -- un pane se cible par son pane_id tmux, jamais par session:window.index.
# Mutation : spawn() recupere l'identifiant du pane cree via un format base sur
# les index plutot que sur #{pane_id}.
# Necessite un vrai serveur tmux (verifie plus haut).
# ---------------------------------------------------------------------------
S="$WORKDIR/s05"; R="$WORKDIR/r05"
cat >"$S" <<'ORDO_EOF'
["split-window", "-t", target, "-c", cwd, "-P", "-F", "#{pane_id}", cmd]
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
["split-window", "-t", target, "-c", cwd, "-P", "-F", "#{session_name}:#{window_index}.#{pane_index}", cmd]
ORDO_EOF
run_case "I5" "un pane se cible par pane_id, jamais session:window.index" \
    "tests.test_panes.InvariantI5Tests.test_invariant_i5_pane_id_survives_close_of_middle_pane" \
    "$LIB_DIR/panes.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I6 -- send-keys du texte et C-m sont deux appels tmux separes. Mutation :
# send() fusionne les deux en un seul appel send-keys.
# Necessite un vrai serveur tmux.
# ---------------------------------------------------------------------------
S="$WORKDIR/s06"; R="$WORKDIR/r06"
cat >"$S" <<'ORDO_EOF'
    _run(["send-keys", "-t", pane_id, "-l", text])
    _run(["send-keys", "-t", pane_id, "C-m"])
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    _run(["send-keys", "-t", pane_id, "-l", text, "C-m"])
ORDO_EOF
run_case "I6" "texte et C-m sont deux appels tmux separes" \
    "tests.test_panes.SendTests.test_invariant_i6_send_keys_two_separate_calls" \
    "$LIB_DIR/panes.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I7 -- un cycle abandonne le graphe entier plutot que d'etre aplati. Mutation :
# depend() cesse de detecter le cycle qu'il vient de creer.
# ---------------------------------------------------------------------------
S="$WORKDIR/s07"; R="$WORKDIR/r07"
cat >"$S" <<'ORDO_EOF'
        cycle = has_cycle(state["taches"])
        if cycle:
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        cycle = None
        if cycle:
ORDO_EOF
run_case "I7" "un cycle abandonne le graphe entier" \
    "tests.test_chantier.TestDependAndCycle.test_i7_cycle_abandonne_le_graphe" \
    "$LIB_DIR/chantier.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I8 -- aucun refus silencieux. Mutation : amend() cesse de refuser de modifier
# le prompt d'une tache en cours d'execution.
# ---------------------------------------------------------------------------
S="$WORKDIR/s08"; R="$WORKDIR/r08"
cat >"$S" <<'ORDO_EOF'
        if task["state"] == "running":
            raise ChantierError(
                f"amend refused: {task_id} is currently running"
            )
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        pass
ORDO_EOF
run_case "I8" "aucun refus silencieux (amend sur tache running)" \
    "tests.test_chantier.TestTaskEdits.test_i8_aucun_refus_silencieux" \
    "$LIB_DIR/chantier.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I9 -- measured et declared ne se melangent jamais. Mutation : status() sert
# measured a la place de declared dans la vue filtree.
# ---------------------------------------------------------------------------
S="$WORKDIR/s09"; R="$WORKDIR/r09"
cat >"$S" <<'ORDO_EOF'
        "declared": list(output["declared"]) if output else [],
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        "declared": list(output["measured"]) if output else [],
ORDO_EOF
run_case "I9" "measured et declared ne se melangent jamais" \
    "tests.test_capteur.TestI9MeasuredDeclaredJamaisMelanges.test_i9_status_garde_measured_et_declared_separes" \
    "$LIB_DIR/capteur.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I10 -- aucune valeur par defaut dans un capteur. Mutation : une cle manquante
# dans la sortie du capteur est comblee par une liste vide au lieu de lever.
# ---------------------------------------------------------------------------
S="$WORKDIR/s10"; R="$WORKDIR/r10"
cat >"$S" <<'ORDO_EOF'
    if missing:
        raise CapteurError(
            "missing key(s) in sensor output: " + ", ".join(missing)
        )
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    for k in missing:
        data[k] = []
ORDO_EOF
run_case "I10" "aucune cle manquante n'est comblee par defaut" \
    "tests.test_capteur.TestI10AucuneValeurParDefaut.test_i10_cle_manquante_est_signalee_pas_comblee" \
    "$LIB_DIR/capteur.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I11 -- le journal distingue ses trois auteurs, ORDO/ORCH/USER, et refuse tout
# le reste. Mutation : write() cesse de verifier l'auteur.
# ---------------------------------------------------------------------------
S="$WORKDIR/s11"; R="$WORKDIR/r11"
cat >"$S" <<'ORDO_EOF'
    if auteur not in _AUTEURS:
        raise chantier.ChantierError(
            f"invalid journal author: {auteur!r}, expected ORDO, ORCH or USER"
        )
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    pass
ORDO_EOF
run_case "I11" "le journal refuse tout auteur hors ORDO/ORCH/USER" \
    "tests.test_journal.TestWrite.test_i11_journal_refuse_auteur_inconnu" \
    "$LIB_DIR/journal.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I12 -- capteur.status() sert le signal filtre, jamais l'etat brut, avant
# adoption. Mutation : le garde-fou d'avant-adoption est court-circuite.
# ---------------------------------------------------------------------------
S="$WORKDIR/s12"; R="$WORKDIR/r12"
cat >"$S" <<'ORDO_EOF'
    if not cap["adopted"]:
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    if False:
ORDO_EOF
run_case "I12" "aucune mesure servie avant adoption du capteur" \
    "tests.test_capteur.TestI12SignalFiltre.test_i12_status_avant_adoption_ne_sert_aucune_mesure" \
    "$LIB_DIR/capteur.py" "$S" "$R"

# ---------------------------------------------------------------------------
# I13 -- briefs et rapports sont ranges par chantier, jamais a plat. Mutation :
# report.path() laisse tomber le segment de chantier, et deux chantiers d'un meme
# ORDO_HOME se disputent alors reports/t-01.json.
# ---------------------------------------------------------------------------
S="$WORKDIR/s13"; R="$WORKDIR/r13"
cat >"$S" <<'ORDO_EOF'
    dossier = store.home() / "reports" / chantier_id
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    dossier = store.home() / "reports"
ORDO_EOF
run_case "I13" "briefs et rapports ranges par chantier, jamais a plat" \
    "tests.test_report.TestPath.test_deux_chantiers_ne_partagent_jamais_un_fichier_de_rapport" \
    "$LIB_DIR/report.py" "$S" "$R"

# ---------------------------------------------------------------------------
# CARTE1 -- la carte n'invente jamais un pane mort. Mutation : sans verificateur
# fourni, la vivacite est devinee "morte" au lieu de rester inconnue. Le graphe
# affiche alors des incidents qui n'ont jamais ete mesures.
# ---------------------------------------------------------------------------
S="$WORKDIR/sc1"; R="$WORKDIR/rc1"
cat >"$S" <<'ORDO_EOF'
            "paneAlive": None if (alive is None or not pane_id) else bool(alive(pane_id)),
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
            "paneAlive": False if (alive is None or not pane_id) else bool(alive(pane_id)),
ORDO_EOF
run_case "CARTE1" "la carte n'invente jamais un pane mort" \
    "tests.test_carte.TestNoeud.test_la_vivacite_du_pane_est_injectee_jamais_devinee" \
    "$LIB_DIR/carte.py" "$S" "$R"

# ---------------------------------------------------------------------------
# CARTE2 -- aucune donnee de l'etat ne peut fermer le script qui la porte.
# Mutation : le JSON part sans encoder "<". Un prompt de tache est du texte qu'un
# modele a ecrit ; qu'il contienne "</script>" n'a rien d'improbable, et il suffit
# a fermer la balise, casser la page, et faire interpreter la suite comme du balisage.
# ---------------------------------------------------------------------------
S="$WORKDIR/sc2"; R="$WORKDIR/rc2"
cat >"$S" <<'ORDO_EOF'
    return brut.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    return brut
ORDO_EOF
run_case "CARTE2" "aucune donnee ne peut fermer le script qui la porte" \
    "tests.test_carte.TestPageDeRendu.test_aucune_donnee_ne_peut_fermer_le_script_qui_la_porte" \
    "$LIB_DIR/carte.py" "$S" "$R"

# ---------------------------------------------------------------------------
# CARTE3 -- une fenetre de service ne passe jamais devant celle des exécutantes.
# Mutation : un index plausible mais pose en tete. _window_id_of() rend alors la
# fenetre de la carte, et l'executante suivante y est splittee.
# ---------------------------------------------------------------------------
S="$WORKDIR/sc3"; R="$WORKDIR/rc3"
cat >"$S" <<'ORDO_EOF'
    cible = (max(indices) + 1) if indices else 1
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    cible = 0
ORDO_EOF
run_case "CARTE3" "la fenetre de carte ne passe jamais devant les exécutantes" \
    "tests.test_panes.SideWindowTests.test_never_takes_an_index_before_the_executor_window" \
    "$LIB_DIR/panes.py" "$S" "$R"

# ---------------------------------------------------------------------------
# CARTE4 -- un pourquoi absent est signale, jamais comble. Mutation : le titre
# fait office d'explication. Un decoupage muet passerait alors pour explique, ce
# qui est pire que muet : plus personne ne verrait qu'il manque quelque chose.
# ---------------------------------------------------------------------------
S="$WORKDIR/sc4"; R="$WORKDIR/rc4"
cat >"$S" <<'ORDO_EOF'
            "why": t.get("why") or "",
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
            "why": t.get("why") or t["titre"],
ORDO_EOF
run_case "CARTE4" "un pourquoi absent est signale, jamais comble" \
    "tests.test_carte.TestPourquoi.test_une_tache_sans_pourquoi_le_dit_au_lieu_de_faire_semblant" \
    "$LIB_DIR/carte.py" "$S" "$R"

# ---------------------------------------------------------------------------
# CARTE5 -- corriger le libelle d'une phase n'efface pas son explication.
# Mutation : why ecrase systematiquement. La seule chose que personne ne
# reecrira disparaitrait au moment ou on croit corriger une faute de frappe.
# ---------------------------------------------------------------------------
S="$WORKDIR/sc5"; R="$WORKDIR/rc5"
cat >"$S" <<'ORDO_EOF'
        groupes[key] = {"label": label, "why": why or ancien_why}
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        groupes[key] = {"label": label, "why": why}
ORDO_EOF
run_case "CARTE5" "renommer une phase n'efface pas son explication" \
    "tests.test_carte.TestGroupes.test_renommer_une_phase_sans_pourquoi_ne_l_efface_pas" \
    "$LIB_DIR/chantier.py" "$S" "$R"

# ---------------------------------------------------------------------------
# SERV1 -- un port ouvert ne suffit pas a conclure qu'Ordo tourne. Mutation : la
# reponse n'est plus lue, seule la connexion compte. Un port pris par un autre
# programme ferait alors renoncer a demarrer le serveur, et la page ne s'ouvrirait
# jamais sans que rien ne dise pourquoi.
# ---------------------------------------------------------------------------
S="$WORKDIR/ss1"; R="$WORKDIR/rs1"
cat >"$S" <<'ORDO_EOF'
            return json.loads(reponse.read()).get("service") == SIGNATURE
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
            return reponse is not None
ORDO_EOF
run_case "SERV1" "un port occupe n'est pas pris pour le serveur d'Ordo" \
    "tests.test_serveur.TestVivacite.test_un_port_pris_par_autre_chose_n_est_pas_pris_pour_ordo" \
    "$LIB_DIR/serveur.py" "$S" "$R"

# ---------------------------------------------------------------------------
# SERV2 -- le parametre home est confronte au registre. Mutation : il est cru sur
# parole, et n'importe quel state.json de la machine devient lisible par qui sait
# former une URL, y compris depuis une page ouverte dans le navigateur.
# ---------------------------------------------------------------------------
S="$WORKDIR/ss2"; R="$WORKDIR/rs2"
cat >"$S" <<'ORDO_EOF'
    if store.canon(home) not in homes():
        raise PermissionError(f"home not registered: {home}")
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    pass
ORDO_EOF
run_case "SERV2" "un ORDO_HOME hors registre ne se lit pas par URL" \
    "tests.test_serveur.TestServeurVivant.test_un_home_hors_registre_est_refuse" \
    "$LIB_DIR/serveur.py" "$S" "$R"

# ---------------------------------------------------------------------------
# SERV3 -- l'en-tete Host est controle. Mutation : il est accepte tel quel, et le
# rebinding DNS rouvre la porte : un site visite dans le navigateur fait resoudre
# son propre nom vers 127.0.0.1 et lit l'etat des chantiers.
# ---------------------------------------------------------------------------
S="$WORKDIR/ss3"; R="$WORKDIR/rs3"
cat >"$S" <<'ORDO_EOF'
        return hote in ("127.0.0.1", "localhost", "::1")
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        return True
ORDO_EOF
run_case "SERV3" "un en-tete Host etranger est refuse" \
    "tests.test_serveur.TestServeurVivant.test_un_en_tete_host_etranger_est_refuse" \
    "$LIB_DIR/serveur.py" "$S" "$R"

# ---------------------------------------------------------------------------
# USAGE1 -- un transcript introuvable se dit inconnu, jamais zero. Mutation : on
# rend des compteurs a zero. Une executante qui tourne depuis vingt minutes
# afficherait alors "0 jeton", ce qui est un chiffre faux presente comme une mesure.
# ---------------------------------------------------------------------------
S="$WORKDIR/su1"; R="$WORKDIR/ru1"
cat >"$S" <<'ORDO_EOF'
        chemin = _trouver(session_id)
        if chemin is None:
            return None
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        chemin = _trouver(session_id)
        if chemin is None:
            return _vide()
ORDO_EOF
run_case "USAGE1" "un transcript introuvable ne devient pas zero jeton" \
    "tests.test_usage.TestLecture.test_un_transcript_absent_rend_rien_plutot_qu_un_zero" \
    "$LIB_DIR/usage.py" "$S" "$R"

# ---------------------------------------------------------------------------
# USAGE2 -- un transcript qui a retreci est relu en entier. Mutation : le decalage
# de lecture est garde tel quel. Il pointerait au milieu d'une ligne d'un fichier
# remplace, et le total resterait faux pour toujours sans que rien ne le signale.
# ---------------------------------------------------------------------------
S="$WORKDIR/su2"; R="$WORKDIR/ru2"
cat >"$S" <<'ORDO_EOF'
    if taille < entree["offset"]:
        entree["offset"] = 0
        entree["totaux"] = _vide()
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    if False:
        pass
ORDO_EOF
run_case "USAGE2" "un transcript remplace est relu en entier" \
    "tests.test_usage.TestLectureIncrementale.test_un_fichier_qui_retrecit_est_relu_en_entier" \
    "$LIB_DIR/usage.py" "$S" "$R"

# ---------------------------------------------------------------------------
# ROUT1 -- le vocabulaire du routage ne se cherche que dans le titre. Mutation :
# la fenetre est elargie au corps du brief. C'est le defaut mesure sur un chantier
# reel de 69 taches : les verbes de conception vivent dans les INTERDICTIONS du
# brief ("ne propose aucune tache de deploiement") et dans la methode ("va voir le
# code"), si bien que 24 taches d'execution sur 24 partaient sur le modele le plus
# cher. Le critere punissait alors les briefs les mieux rediges.
# ---------------------------------------------------------------------------
S="$WORKDIR/sr1"; R="$WORKDIR/rr1"
cat >"$S" <<'ORDO_EOF'
    demande = _plat(titre)
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    demande = _plat(f"{titre}\n{prompt}")
ORDO_EOF
run_case "ROUT1" "le vocabulaire du routage se lit dans le titre, pas dans le brief" \
    "tests.test_routage.TestLeCorpsDuBriefNestPasLaDemande" \
    "$LIB_DIR/routage.py" "$S" "$R"

# ---------------------------------------------------------------------------
# ROUT2 -- une tache relancee monte d'un cran. Mutation : l'escalade est retiree.
# Une tache mal classee vers le bas se relancerait alors a l'identique, referait
# exactement le meme echec, et le facturerait une seconde fois sans que rien ne
# signale que le modele etait en cause.
# ---------------------------------------------------------------------------
S="$WORKDIR/sr2"; R="$WORKDIR/rr2"
cat >"$S" <<'ORDO_EOF'
    rang = min(MODELES.index(modele) + essais, len(MODELES) - 1)
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    rang = MODELES.index(modele)
ORDO_EOF
run_case "ROUT2" "une tache relancee ne repart pas sur le modele qui vient d'echouer" \
    "tests.test_routage.TestEscaladeSurRelance" \
    "$LIB_DIR/routage.py" "$S" "$R"

# ---------------------------------------------------------------------------
# DIGEST1 -- un identifiant de tache ne sort jamais sans son titre. Mutation :
# le titre disparait du rendu. L'humain relit alors "t-33" sans savoir de quoi
# il s'agit, ce qui est exactement le defaut que le module existe pour fermer.
# ---------------------------------------------------------------------------
S="$WORKDIR/sd1"; R="$WORKDIR/rd1"
cat >"$S" <<'ORDO_EOF'
    return f"{identifiant} « {titre or 'no title'} »"
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    return f"{identifiant}"
ORDO_EOF
run_case "DIG1" "un identifiant de tache ne sort jamais sans son titre" \
    "tests.test_situation.RenderTest.test_render_ne_cite_aucun_identifiant_nu" \
    "$LIB_DIR/situation.py" "$S" "$R"

# ---------------------------------------------------------------------------
# DIGEST2 -- une question de l'orchestratrice ne sonne pas chez l'humain.
# Mutation : le filtre pourHumain saute. Le digest reclame alors une decision
# a l'humain pour une question qui appartenait a l'orchestratrice, et une
# fausse alerte coute plus cher qu'un silence.
# ---------------------------------------------------------------------------
S="$WORKDIR/sd2"; R="$WORKDIR/rd2"
cat >"$S" <<'ORDO_EOF'
        if q["chantier"] != chantier_id or not q.get("pourHumain"):
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        if q["chantier"] != chantier_id:
ORDO_EOF
run_case "DIG2" "une question de l'orchestratrice ne sonne pas chez l'humain" \
    "tests.test_situation.ForHumanTest.test_question_pour_l_orchestratrice_n_atteint_pas_l_humain" \
    "$LIB_DIR/situation.py" "$S" "$R"

echo ""
echo "Interdits du brief d'executante (SPEC.md section 5, ordo/prompt.py) :"
echo ""

# ---------------------------------------------------------------------------
# Interdit 1 -- AskUserQuestion n'existe pas hors interactif. Mutation : le mot
# disparait du brief, comme le reste de l'interdit textuel.
# ---------------------------------------------------------------------------
S="$WORKDIR/s13"; R="$WORKDIR/r13"
cat >"$S" <<'ORDO_EOF'
        "1. AskUserQuestion does not exist in your session: the tool is absent "
        "outside interactive mode, you look for it, you do not find it, you give up "
        "without delivering anything. If you need to ask something, write "
        "\"state\": \"asking\" in your report, a clear question in \"question\", and "
        "END YOUR TURN. Never look for AskUserQuestion.\n"
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        "1. That tool does not exist in your session: it is absent "
        "outside interactive mode, you look for it, you do not find it, you give up "
        "without delivering anything. If you need to ask something, write "
        "\"state\": \"asking\" in your report, a clear question in \"question\", and "
        "END YOUR TURN. Never look for that tool.\n"
ORDO_EOF
run_case "INT1" "interdit : AskUserQuestion absent hors interactif" \
    "tests.test_prompt.TestBriefExecutante.test_askuserquestion_interdit_dans_le_brief" \
    "$LIB_DIR/prompt.py" "$S" "$R"

# ---------------------------------------------------------------------------
# Interdit 2 -- une executante ne s'autovalide jamais. Mutation : le mot
# disparait du brief.
# ---------------------------------------------------------------------------
S="$WORKDIR/s14"; R="$WORKDIR/r14"
cat >"$S" <<'ORDO_EOF'
        "2. You never self-validate. You never declare your own work compliant with "
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        "2. You never judge yourself. You never declare your own work compliant with "
ORDO_EOF
run_case "INT2" "interdit : autovalidation" \
    "tests.test_prompt.TestBriefExecutante.test_autovalidation_interdite_dans_le_brief" \
    "$LIB_DIR/prompt.py" "$S" "$R"

# ---------------------------------------------------------------------------
# Interdit 3 -- rien d'irreversible ni d'externe sans poser la question.
# Mutation : le mot disparait du brief.
# ---------------------------------------------------------------------------
S="$WORKDIR/s15"; R="$WORKDIR/r15"
cat >"$S" <<'ORDO_EOF'
        "6. Nothing irreversible or external without asking through the report: no "
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        "6. Nothing special or external without asking through the report: no "
ORDO_EOF
run_case "INT3" "interdit : acte irreversible sans question" \
    "tests.test_prompt.TestBriefExecutante.test_irreversible_sans_question_interdit_dans_le_brief" \
    "$LIB_DIR/prompt.py" "$S" "$R"

# ---------------------------------------------------------------------------
# REG1 -- ouvrir un chantier l'inscrit au registre du serveur de cartes.
# Mutation : l'appel disparaît de cmd_start. Le chantier tourne alors sans
# figurer dans aucun menu, exactement le défaut qui a coûté un diagnostic.
# ---------------------------------------------------------------------------
S="$WORKDIR/s16"; R="$WORKDIR/r16"
cat >"$S" <<'ORDO_EOF'
    _inscrire_au_registre()
    if args.json:
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    if args.json:
ORDO_EOF
run_case "REG1" "ouvrir un chantier l'inscrit au registre" \
    "tests.test_cli.TestChantierVerbs.test_start_inscrit_le_home_au_registre_du_serveur" \
    "$LIB_DIR/cli.py" "$S" "$R"

# ---------------------------------------------------------------------------
# REG2 -- inscrire, jamais allumer. Mutation : ensure() à la place de
# register(). Ouvrir un chantier démarrerait un daemon que personne n'a demandé.
# ---------------------------------------------------------------------------
S="$WORKDIR/s17"; R="$WORKDIR/r17"
cat >"$S" <<'ORDO_EOF'
        serveur.register(store.home())
    except Exception as exc:  # noqa: BLE001 - voir le commentaire ci-dessus
        print(f"map registry unavailable: {exc}", file=sys.stderr, flush=True)
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
        serveur.ensure()
    except Exception as exc:  # noqa: BLE001 - voir le commentaire ci-dessus
        print(f"map registry unavailable: {exc}", file=sys.stderr, flush=True)
ORDO_EOF
run_case "REG2" "start inscrit sans jamais allumer de serveur" \
    "tests.test_cli.TestChantierVerbs.test_start_n_allume_aucun_serveur" \
    "$LIB_DIR/cli.py" "$S" "$R"

# ---------------------------------------------------------------------------
# REG3 -- ORDO_NO_SERVE coupe l'inscription. Mutation : la garde saute, et une
# suite de tests écrit dans le registre réel de la machine.
# ---------------------------------------------------------------------------
S="$WORKDIR/s18"; R="$WORKDIR/r18"
cat >"$S" <<'ORDO_EOF'
    if os.environ.get("ORDO_NO_SERVE"):
        return
    try:
        from . import serveur
ORDO_EOF
cat >"$R" <<'ORDO_EOF'
    try:
        from . import serveur
ORDO_EOF
run_case "REG3" "ORDO_NO_SERVE coupe l'inscription de start" \
    "tests.test_cli.TestChantierVerbs.test_start_sous_ORDO_NO_SERVE_n_inscrit_rien" \
    "$LIB_DIR/cli.py" "$S" "$R"

echo ""
echo "Vérification de restauration finale :"
restore_lib_tree
RESTORE_RC=$?
RESTORE_ALREADY_DONE=1

echo ""
echo "Total : $COUVERTS/$TOTAL invariants prouves par mutation, $NON_COUVERTS non couverts."
if [ "$NON_COUVERTS" -gt 0 ]; then
    echo "Non couverts :"
    for nom in "${NON_COUVERTS_NOMS[@]}"; do
        echo "  - $nom"
    done
fi

FINAL_RC=0
if [ "$NON_COUVERTS" -gt 0 ] || [ "$RESTORE_RC" -ne 0 ]; then
    FINAL_RC=1
fi
exit "$FINAL_RC"
